"""empty message

Revision ID: 77400529fad5
Revises: 865d0a49ffe5
Create Date: 2025-11-20 11:00:37.099931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77400529fad5'
down_revision = '865d0a49ffe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_email_key'), type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('user_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
